from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("services/", views.services, name="services"),
    path("contact/", views.contact, name="contact"),
    path("blog/", views.blog, name="blog"),
    path("blog-single/", views.blog_single, {"slug": "default"}, name="blog_single"),
    path("blog/<slug:slug>/", views.blog_single, name="blog_single_slug"),
    path("testimonials/", views.testimonials, name="testimonials"),
    path("pricing/", views.pricing, name="pricing"),
    path("faqs/", views.faqs, name="faqs"),
    path("products/", views.products, name="products"),
    path("category/<slug:slug>/", views.category_products, name="category_products"),
    path("product-single/", views.product_single, name="product_single"),
    path("team/", views.team, name="team"),
    path("team-single/", views.team_single, name="team_single"),
    path("service-single/", views.service_single, name="service_single"),
    path("image-gallery/", views.image_gallery, name="image_gallery"),
    path("video-gallery/", views.video_gallery, name="video_gallery"),
    path("404/", views.page_not_found, name="page_not_found"),
    path("admin-login/", views.admin_login, name="admin_login"),
    path("admin-logout/", views.admin_logout, name="admin_logout"),
    path("dashboard/", views.admin_dashboard, name="admin_dashboard"),
    path("dashboard/categories/", views.category_list, name="category_list"),
    path("dashboard/categories/add/", views.category_create, name="category_create"),
    path("dashboard/categories/<int:pk>/edit/", views.category_update, name="category_update"),
    path("dashboard/categories/<int:pk>/delete/", views.category_delete, name="category_delete"),
    path("dashboard/sellers/", views.seller_list, name="seller_list"),
    path("dashboard/sellers/add/", views.seller_create, name="seller_create"),
    path("dashboard/sellers/<int:pk>/edit/", views.seller_update, name="seller_update"),
    path("dashboard/sellers/<int:pk>/delete/", views.seller_delete, name="seller_delete"),
    path("dashboard/products/", views.product_list, name="product_list"),
    path("dashboard/products/add/", views.product_create, name="product_create"),
    path("dashboard/products/<int:pk>/edit/", views.product_update, name="product_update"),
    path("dashboard/products/<int:pk>/delete/", views.product_delete, name="product_delete"),
    path("dashboard/blogs/", views.blog_list, name="blog_list"),
    path("dashboard/blogs/add/", views.blog_create, name="blog_create"),
    path("dashboard/blogs/<int:pk>/edit/", views.blog_update, name="blog_update"),
    path("dashboard/blogs/<int:pk>/delete/", views.blog_delete, name="blog_delete"),
    path("dashboard/testimonials/", views.testimonial_list, name="testimonial_list"),
    path("dashboard/testimonials/add/", views.testimonial_create, name="testimonial_create"),
    path("dashboard/testimonials/<int:pk>/edit/", views.testimonial_update, name="testimonial_update"),
    path("dashboard/testimonials/<int:pk>/delete/", views.testimonial_delete, name="testimonial_delete"),
    path("dashboard/contacts/", views.contact_list, name="contact_list"),
    path("dashboard/contacts/<int:pk>/delete/", views.contact_delete, name="contact_delete"),
    path("dashboard/team/", views.team_list, name="team_list"),
    path("dashboard/team/add/", views.team_create, name="team_create"),
    path("dashboard/team/<int:pk>/edit/", views.team_update, name="team_update"),
    path("dashboard/team/<int:pk>/delete/", views.team_delete, name="team_delete"),
]
