# Generated by Django 6.0.3 on 2026-05-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_in_bulk_app', '0003_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='description',
        ),
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
