# Generated by Django 6.0.3 on 2026-05-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_in_bulk_app', '0005_category_description_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
