# Generated by Django 6.0.3 on 2026-05-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_in_bulk_app', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
